# Configuration for sparse weights training
project_name: 'sparse-weights'

# Pruning parameters
pruning:
  target_sparsity: 0.5
  warmup_ratio: 0.15
  final_prune_ratio: 0.85
  prune_applications: 10

# Training parameters
training:
  epochs: 20
  batch_size: 128
  seq_len: 512
  lr: 0.0005
  weight_decay: 0.01
  warmup_steps: 500
  device: 'cuda'
  use_bf16: true
  gradient_clip_norm: 1.0

paths:
  output_dir: 'exp'

# Model settings
model:
  config_name: 'gpt2'
  tokenizer_name: 'gpt2'

# Logging settings
logging:
  level: 'INFO'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: null  # null = console only