# Configuration for sparse weights training
project_name: 'sparse-weights'

# Pruning parameters
pruning:
  target_sparsity: 0.5
  warmup_ratio: 0.10
  final_prune_ratio: 0.85
  prune_applications: 10

# Training parameters
training:
  epochs: 50
  batch_size: 32
  seq_len: 128
  lr: 0.001
  device: 'cuda'

paths:
  output_dir: 'exp'

# Model settings
model:
  config_name: 'gpt2'
  tokenizer_name: 'gpt2'

# Logging settings
logging:
  level: 'INFO'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: null  # null = console only